/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import javax.swing.JOptionPane;

/**
 *
 * @author Djordje Janjic
 */
public class FrmRegister extends javax.swing.JDialog {

    /**
     * Creates new form FrmRegister
     */
    public FrmRegister(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        arrangeForm();
        setLabels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelRegister = new javax.swing.JPanel();
        lblFirstName = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblPasswordAgain = new javax.swing.JLabel();
        lblErrorLastName = new javax.swing.JLabel();
        lblErrorPassword = new javax.swing.JLabel();
        lblErrorFirstName = new javax.swing.JLabel();
        lblErrorPasswordAgain = new javax.swing.JLabel();
        lblErrorUsername = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtPasswordAgain = new javax.swing.JPasswordField();
        lblBckg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jpanelRegister.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFirstName.setFont(new java.awt.Font("Montserrat Alternates SemiBold", 0, 12)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstName.setText("Ime");
        jpanelRegister.add(lblFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        btnRegister.setBackground(new java.awt.Color(0, 153, 51));
        btnRegister.setFont(new java.awt.Font("Montserrat Alternates Medium", 0, 14)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Registruj se");
        btnRegister.setBorder(null);
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jpanelRegister.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 130, 30));

        btnCancel.setBackground(new java.awt.Color(0, 153, 51));
        btnCancel.setFont(new java.awt.Font("Montserrat Alternates Medium", 0, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Izađi");
        btnCancel.setBorder(null);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jpanelRegister.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 130, 30));

        txtName.setFont(new java.awt.Font("Montserrat Alternates SemiBold", 0, 12)); // NOI18N
        jpanelRegister.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 230, -1));

        txtLastName.setFont(new java.awt.Font("Montserrat Alternates SemiBold", 0, 12)); // NOI18N
        jpanelRegister.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 230, -1));

        lblLastName.setFont(new java.awt.Font("Montserrat Alternates SemiBold", 0, 12)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(255, 255, 255));
        lblLastName.setText("Prezime");
        jpanelRegister.add(lblLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        txtUsername.setFont(new java.awt.Font("Montserrat Alternates SemiBold", 0, 12)); // NOI18N
        jpanelRegister.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 230, -1));

        lblUsername.setFont(new java.awt.Font("Montserrat Alternates SemiBold", 0, 12)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Korisničko ime");
        jpanelRegister.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        lblPassword.setFont(new java.awt.Font("Montserrat Alternates SemiBold", 0, 12)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Lozinka");
        jpanelRegister.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        lblPasswordAgain.setFont(new java.awt.Font("Montserrat Alternates SemiBold", 0, 12)); // NOI18N
        lblPasswordAgain.setForeground(new java.awt.Color(255, 255, 255));
        lblPasswordAgain.setText("Ponovi lozinku");
        jpanelRegister.add(lblPasswordAgain, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        lblErrorLastName.setFont(new java.awt.Font("Montserrat Alternates Light", 0, 12)); // NOI18N
        lblErrorLastName.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorLastName.setText("jLabel1");
        jpanelRegister.add(lblErrorLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        lblErrorPassword.setFont(new java.awt.Font("Montserrat Alternates Light", 0, 12)); // NOI18N
        lblErrorPassword.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorPassword.setText("jLabel1");
        jpanelRegister.add(lblErrorPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        lblErrorFirstName.setFont(new java.awt.Font("Montserrat Alternates Light", 0, 12)); // NOI18N
        lblErrorFirstName.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorFirstName.setText("jLabel1");
        jpanelRegister.add(lblErrorFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        lblErrorPasswordAgain.setFont(new java.awt.Font("Montserrat Alternates Light", 0, 12)); // NOI18N
        lblErrorPasswordAgain.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorPasswordAgain.setText("jLabel1");
        jpanelRegister.add(lblErrorPasswordAgain, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        lblErrorUsername.setFont(new java.awt.Font("Montserrat Alternates Light", 0, 12)); // NOI18N
        lblErrorUsername.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorUsername.setText("jLabel1");
        jpanelRegister.add(lblErrorUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));
        jpanelRegister.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 230, -1));
        jpanelRegister.add(txtPasswordAgain, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 230, -1));

        lblBckg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/deficit_register.png"))); // NOI18N
        lblBckg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jpanelRegister.add(lblBckg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        String firstName = txtName.getText().trim();
        String lastName = txtLastName.getText().trim();
        String username = txtUsername.getText().trim();
        String password = String.copyValueOf(txtPassword.getPassword());
        String passwordAgain = String.copyValueOf(txtPasswordAgain.getPassword());
        
        setLabels();
        checkInput(firstName, lastName, username, password, passwordAgain);
        
        if(firstName.isEmpty() || lastName.isEmpty() || username.isEmpty() || password.isEmpty() || passwordAgain.isEmpty()){
            JOptionPane.showMessageDialog(this, "Morate uneti sva polja!");
            return;
        }
        
        
        
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void arrangeForm() {
        setLocationRelativeTo(this);   
        dispose();
        setSize(295, 500);
        setUndecorated(true);
        //setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRegister;
    private javax.swing.JPanel jpanelRegister;
    private javax.swing.JLabel lblBckg;
    private javax.swing.JLabel lblErrorFirstName;
    private javax.swing.JLabel lblErrorLastName;
    private javax.swing.JLabel lblErrorPassword;
    private javax.swing.JLabel lblErrorPasswordAgain;
    private javax.swing.JLabel lblErrorUsername;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPasswordAgain;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPasswordAgain;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private void setLabels() {
        lblErrorFirstName.setText("");
        lblErrorLastName.setText("");
        lblErrorPassword.setText("");
        lblErrorPasswordAgain.setText("");
        lblErrorUsername.setText("");     
    }

    private void checkInput(String firstName, String lastName, String username, String password, String passwordAgain) {
        
        if(!password.equals(passwordAgain)){
            JOptionPane.showMessageDialog(this, "Lozinke se ne podudaraju!");
            return;
        }
        
        if(firstName.isEmpty())
            lblErrorFirstName.setText("Morate uneti ime");
        else
            lblErrorFirstName.setText("");
        if(lastName.isEmpty())
            lblErrorLastName.setText("Morate uneti prezime");
        else
            lblErrorLastName.setText("");
        if(username.isEmpty())
            lblErrorUsername.setText("Morate uneti korisničko ime");
        else
            lblErrorUsername.setText("");
        if(password.isEmpty())
            lblErrorPassword.setText("Morate uneti lozinku");
        else
            lblErrorPassword.setText("");
        if(passwordAgain.isEmpty())
            lblErrorPasswordAgain.setText("Morate ponoviti lozinku");
        else
            lblErrorPasswordAgain.setText("");    
    }
}
